name: Test Project
on: workflow_dispatch
jobs:
  show-time:
    runs-on: ubuntu-latest
    steps:
      - name: Running time
        run: |
          dt=$(date '+%d/%m/%Y %H:%M:%S');
          echo "$dt"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        # with: pass
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        # better safe than npm install
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    # set needs for working after another job
    needs: ["show-time", "test"]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Dploying..."
